### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by freyandhy** [farridkun/challenge-javascript-collabs#1]
Saran perbaikan, @farridkun @aridarsan :
- Parameter constructor bisa menggunakan tipe data object
- Proses remove hobby bisa menggunakan versi ES6.

~ Practice Make Perfect ~ 👍

**Comment by farridkun** [comment]
Baik mas @freyandhy terima kasih atas masukannya akan coba saya atau kami pelajari dan implementasikan kembali agar makin mantap 🙌😀
